USE [master]
GO
GO
IF DB_ID (N'ProductScanDB') IS NOT NULL
	DROP DATABASE ProductScanDB;
GO


CREATE DATABASE [ProductScanDB]
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ProductScanDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ProductScanDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ProductScanDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ProductScanDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ProductScanDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ProductScanDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [ProductScanDB] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [ProductScanDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ProductScanDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ProductScanDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ProductScanDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ProductScanDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ProductScanDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ProductScanDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ProductScanDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ProductScanDB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [ProductScanDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ProductScanDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ProductScanDB] SET TRUSTWORTHY ON 
GO

ALTER DATABASE [ProductScanDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ProductScanDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ProductScanDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [ProductScanDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ProductScanDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ProductScanDB] SET  MULTI_USER 
GO

ALTER DATABASE [ProductScanDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ProductScanDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ProductScanDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ProductScanDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [ProductScanDB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [ProductScanDB] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ProductScanDB] SET  READ_WRITE 
GO


